version: '3.8'

services:
  web:
    image: shop-sphere:latest
    container_name: shopsphere-prod
    expose:
      - "8000"
    volumes:
      - /opt/shop-sphere/uploads:/app/uploads
      - /opt/shop-sphere/logs/nginx:/var/log/nginx
      - /opt/shop-sphere/logs/supervisor:/var/log/supervisor
      - /opt/shop-sphere/.env:/app/.env:ro
    environment:
      - SERVER_ENVIRONMENT=PROD
      - PYTHONPATH=/app
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ALIBABA_CLOUD_ACCESS_KEY_ID=${OSS_ACCESS_KEY_ID}
      - ALIBABA_CLOUD_ACCESS_KEY_SECRET=${OSS_ACCESS_KEY_SECRET}
      - OSS_BUCKET_NAME=${OSS_BUCKET_NAME}
      - OSS_ENDPOINT=${OSS_ENDPOINT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - DEEPSEEK_BASE_URL=${DEEPSEEK_BASE_URL}
    env_file:
      - /opt/shop-sphere/.env
    networks:
      shopsphere-net:
        aliases:
          - web
    restart: unless-stopped

  # Nginx反向代理（使用阿里云优化镜像的特殊配置）
  nginx:
    image: alibaba-cloud-linux-3-registry.cn-hangzhou.cr.aliyuncs.com/alinux3/nginx_optimized:20240221-1.20.1-2.3.0
    container_name: shopsphere-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/shop-sphere/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/shop-sphere/uploads:/var/www/uploads:ro
      - /opt/shop-sphere/logs/nginx:/var/log/nginx
    command: nginx_keentune.sh
    depends_on:
      - web
    networks:
      shopsphere-net:
        aliases:
          - nginx
    restart: unless-stopped

networks:
  shopsphere-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
